project:
  type: website

website:
  # title: "personal website"
  navbar:
    left:
      - href: index.qmd
        text: home
      - href: projects.qmd
        text: projects
        
  page-footer:
    right: "&copy; 2025, Mackenzie Lindholm"

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: false
    published-title: "last updated"
    reference-location: document
    code-fold: false
    code-summary: ""
    fontsize: 1.3em

editor: visual

execute: 
  freeze: auto